### ISSUE TITLE
Parameters setting in new datasets

### ISSUE THREAD

**Issue by LeisureGong** [amgt-d1/Ex-DPC-plus-plus#1]
Hello, I want to run Ex-DPC-plus-plus in new dataset.  The parameters \rho_min and \delta_min are fixed in your demo dataset. I wonder how to specify \rho_min and \delta_min in new dataset.
Hope to receive your reply. Thank You !

**Comment by amgt-d1** [comment]
Thank you for your interests!
In exdpc.hpp, please "ctrl F" + "determine delta_min & rho_min".
Then you can find them.

**Comment by LeisureGong** [comment]
Sorry, I didn't state the question clearly.  I wonder that how to set  proper **rho_min** and **delta_min** parameters in new datasets.  
If we predefine a proper **cutoff**  on a dataset which has k clusters,  the value of <**rho_min**, **delta_min**> is equal to the k largest **rho*delta** ?

Thank you. Looking forward to receiving your reply !

**Comment by amgt-d1** [comment]
I used a decision graph to determine delta_min and rho_min.
